// 共享电影数据
// 这个文件在 index.html、detail.html 和 favorites.html 中被复用，避免重复维护。
const moviesData = [
    {
        id: 1,
        title: "The Circus",
        year: 1928,
        genre: "Comedy",
        overview: "《马戏团》讲述流浪汉意外闯入马戏团后成为笑料明星，却在爱情与生计之间不断碰壁的故事。影片延续卓别林标志性的肢体喜剧和温柔的人道主义视角，在密集笑点中包裹着孤独、善良与成全，是默片时代喜剧艺术的代表作之一。",
        director: "查理·卓别林",
        cast: "查理·卓别林、门娜·肯尼迪、艾德娜·珀薇安丝",
        rating: "⭐⭐⭐⭐⭐ 9.2",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/Circle_hb_h.png",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/Circle_hb_s.png",
        hlsUrl: "https://r2.2ya.top/hls/the-circus/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        subtitleUrl: "",
        fallbackVideoUrl: ""
    },
    {
        id: 2,
        title: "All Quiet on the Western Front",
        year: 1930,
        genre: "Drama",
        overview: "《西线无战事》是一部关于战争的电影，讲述了士兵们在战场上进行战斗的故事。根据埃里希·玛丽亚·雷马克的同名小说改编，影片以第一次世界大战为背景，通过一个普通德国士兵的视角，真实而深刻地反映了战争的残酷性与毁灭性。影片不仅展现了战争中的血腥与死亡，更重要的是揭示了战争对人性的摧残。这部影片开创了战争电影的新纪元，其反战主题在当时引起了巨大的社会反响。",
        director: "刘易斯·迈尔斯通",
        cast: "莱万·艾伦、路易斯·沃尔海姆、约翰·威斯利",
        rating: "⭐⭐⭐⭐⭐ 8.9",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/all_quiet_backdrop.jpg?v=20260524",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/all_quiet_poster.jpg?v=20260524",
        hlsUrl: "https://r2.2ya.top/hls/west_no_war/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        subtitleUrl: "subtitles/west_no_war.vtt",
        fallbackVideoUrl: ""
    },
    {
        id: 3,
        title: "Metropolis",
        year: 1927,
        genre: "Sci-Fi",
        overview: "《大都会》是一部德国表现主义科幻杰作，设定在未来的摩天楼城市，通过对现代社会阶级分化的讽刺描绘，探讨了资本主义社会中阶级冲突的问题。影片具有超前的视觉设计和宏大的场景制作，深刻影响了后世科幻电影的发展，被认为是电影史上最重要的作品之一。",
        director: "弗里茨·朗",
        cast: "古斯塔夫·弗勒利希、布里吉特·海姆、阿尔弗雷德·阿贝尔",
        rating: "⭐⭐⭐⭐⭐ 8.5",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/Metropolis_backdrop.jpg",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/Metropolis_poster.jpg",
        hlsUrl: "https://r2.2ya.top/hls/metropolis/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        subtitleUrl: "",
        fallbackVideoUrl: ""
    },
    {
        id: 4,
        title: "Nosferatu",
        year: 1922,
        genre: "Horror",
        overview: "《诺斯费拉图》是电影史上第一部吸血鬼电影，改编自勃拉姆·斯托克的经典小说《德古拉》。影片运用了表现主义的视觉手法，营造出压抑而诡异的恐怖氛围。虽然这是一部默片，但导演弗里茨·穆瑙通过精妙的镜头语言、灯光设计和美术指导，创造了一个令人毛骨悚然的吸血鬼形象，至今仍被认为是恐怖电影的经典之作。",
        director: "弗里茨·穆瑙",
        cast: "马克斯·施雷克、古斯塔夫·冯·瓦根海姆、格雷塔·施罗德-马坦",
        rating: "⭐⭐⭐⭐ 8.0",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/Nosferatu_backdrop.jpg",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/Nosferatu_poster.jpg",
        hlsUrl: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/hls/nosferatu/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        subtitleUrl: "",
        fallbackVideoUrl: ""
    },
    {
        id: 5,
        title: "Modern Times",
        year: 1936,
        genre: "Comedy",
        overview: "《摩登时代》是卓别林最后一部默片，也是他对工业时代社会的深刻讽刺。影片讲述了一个工厂工人在现代化生产线中的困境与挣扎，通过幽默夸张的表演手法，揭露了机器时代对人性的压抑。影片将喜剧与社会批评完美融合，既能让观众发笑，又能引发深刻的思考。这部影片标志着默片时代的终结，也是卓别林艺术成就的巅峰之作。",
        director: "查理·卓别林",
        rating: "⭐⭐⭐⭐⭐ 9.0",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/modern_times_backdrop.jpg",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/modern_times_poster.jpg",
        hlsUrl: "https://r2.2ya.top/hls/modern-times/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        fallbackVideoUrl: ""
    },
    {
        id: 6,
        title: "Frankenstein",
        year: 1931,
        genre: "Horror",
        overview: "《弗兰肯斯坦》改编自玛丽·雪莱的经典小说，讲述科学家维克多·弗兰肯斯坦创造生命后无法面对后果，最终引发悲剧的故事。影片以阴郁的哥特氛围、强烈的光影造型和鲍里斯·卡洛夫令人难忘的表演，塑造了影史最具代表性的怪物形象之一，也让科学伦理与孤独恐惧成为恐怖电影的重要母题。",
        director: "詹姆斯·惠尔",
        cast: "科林·克莱夫、鲍里斯·卡洛夫、梅·克拉克",
        rating: "⭐⭐⭐⭐ 7.8",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/frankenstein_backdrop.jpg",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/frankenstein_poster.jpg",
        hlsUrl: "https://r2.2ya.top/hls/frankenstein/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        fallbackVideoUrl: ""
    },
    {
        id: 7,
        title: "The General",
        year: 1926,
        genre: "Action",
        overview: "《将军号》由巴斯特·基顿主演并联合执导，故事取材于美国南北战争时期的火车追逐事件。影片将冒险、爱情、战争场面和精密的机械喜剧融为一体，大量实景特技至今仍令人惊叹。基顿冷面笑匠式的表演与严密的动作调度，使这部作品成为默片动作喜剧的巅峰之一。",
        director: "巴斯特·基顿、克莱德·布鲁克曼",
        cast: "巴斯特·基顿、玛丽昂·梅克、格伦·卡范",
        rating: "⭐⭐⭐⭐⭐ 8.7",
        backdrop: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/backdrops/the_general_backdrop.jpg",
        poster: "https://pub-c8dff8c2f0a44d65a2aa76008f27ed86.r2.dev/posters/the_general_poster.jpg",
        hlsUrl: "https://r2.2ya.top/hls/the-general/index.m3u8",
        videoUrl: "",
        audioUrl: "",
        subtitleUrl: "",
        fallbackVideoUrl: ""
    }
];
